### PR TITLE
Remove cachex dep

### PR DESCRIPTION
**Pull request by josevalim**
It seems the cachex usage was very simply and that an agent could suffice,
so I gave it a try. I may be missing something here though, so feel free to close
this.

### CODE REVIEW

**Comment by josevalim** [comment]
Another approach is to remove the BatchCache altogether and simply keep the state inside the HTTPBackend. This way you don't need extra processes and stuff. :)

**Comment by chasers** [comment]
Yeah we were doing this to minimize ram as much as possible by not stashing stuff in state. I guess this shouldn't get crazy since Logger events get evicted if too many come in too fast.

**Comment by josevalim** [comment]
If cachex uses ETS, a copy is still made every time you read and write to it. There would be no copying only if using persistent_term.

**Comment by chasers** [comment]
Roger ... okay the only other concern was throughput. We were worried about the genserver becoming a bottleneck. Maybe because the upstream logger gen server runs everything through it, this would not be a concern?

**Comment by josevalim** [comment]
Right, I don't think it will be a botlleneck but a concern in all of these solutions is that sending the log messages to a separate process or ETS will occur extra copying, both when writing and when reading.

So ideally we would get rid of the process altogether and keep it within the backend state itself. We could still have a separate module to deal with the state and the state could be opaque to the backend, but it wouldn't use another process.

**Comment by chasers** [comment]
Alrighty, let's do it! 🙏

**Pull request merged**
